// Data store for Waypoint Store Manager Portal across 3 brands: Fresh, Style, and Tech

export const OUTLETS = [
  {
    id: 'OUT047',
    name: 'Waypoint Fresh – Kandy Town',
    brand: 'Waypoint Fresh',
    category: 'Supermarket',
    district: 'Kandy',
    hub: 'Kandy Regional Hub',
    address: 'Dalada Veediya, beside Clock Tower, Kandy',
    manager: 'Anjali Silva',
    phone: '+94 71 890 1234',
    accessConstraint: 'Van Only',
    dockType: 'Rear Dock (Bay B)',
    deliveryWindow: '05:45 AM – 07:01 AM',
    mustArriveBefore: '08:00 AM',
    receivingPin: '4829',
    consecutiveSkips: 0,
  },
  {
    id: 'OUT-4089',
    name: 'Waypoint Fresh – Nugegoda',
    brand: 'Waypoint Fresh',
    category: 'Supermarket',
    district: 'Colombo',
    hub: 'Peliyagoda Central DC',
    address: '142 High Level Road, Nugegoda',
    manager: 'D. Perera',
    phone: '+94 77 234 5678',
    accessConstraint: 'Standard Rigid Truck',
    dockType: 'Rear Dock',
    deliveryWindow: '06:15 AM – 07:45 AM',
    mustArriveBefore: '08:00 AM',
    receivingPin: '6194',
    consecutiveSkips: 0,
  },
  {
    id: 'OUT-2041',
    name: 'Waypoint Style – Colombo City Centre',
    brand: 'Waypoint Style',
    category: 'Apparel & Fashion',
    district: 'Colombo',
    hub: 'Peliyagoda Central DC',
    address: 'Mall Level 2, 137 Sir James Pieris Mawatha, Colombo 02',
    manager: 'T. Alwis',
    phone: '+94 76 543 2109',
    accessConstraint: 'Shared Mall Loading Bay',
    dockType: 'Mall Loading Bay',
    deliveryWindow: '07:00 AM – 09:00 AM',
    mustArriveBefore: '10:00 AM (Mall Opening)',
    receivingPin: '3318',
    consecutiveSkips: 0,
  },
  {
    id: 'OUT-2015',
    name: 'Waypoint Style – Kandy City Centre',
    brand: 'Waypoint Style',
    category: 'Apparel & Fashion',
    district: 'Kandy',
    hub: 'Kandy Regional Hub',
    address: 'Lower Ground, 5 Dalada Veediya, Kandy',
    manager: 'S. Dissanayake',
    phone: '+94 70 882 1144',
    accessConstraint: 'Basement Bay (Max H 3.2m)',
    dockType: 'Mall Bay',
    deliveryWindow: '06:30 AM – 08:30 AM',
    mustArriveBefore: '09:30 AM',
    receivingPin: '8241',
    consecutiveSkips: 0,
  },
  {
    id: 'OUT-1029',
    name: 'Waypoint Tech – Liberty Plaza',
    brand: 'Waypoint Tech',
    category: 'Consumer Electronics & Appliances',
    district: 'Colombo',
    hub: 'Peliyagoda Central DC',
    address: 'Ground Floor, 250 R.A. De Mel Mawatha, Colombo 03',
    manager: 'M. Fernando',
    phone: '+94 77 912 3456',
    accessConstraint: 'Tail-lift Required',
    dockType: 'Rear Service Dock',
    deliveryWindow: '09:00 AM – 11:30 AM',
    mustArriveBefore: '12:00 PM',
    receivingPin: '7503',
    consecutiveSkips: 1, // Flagged for disruption scenario
  },
  {
    id: 'OUT-1044',
    name: 'Waypoint Tech – Kollupitiya Central',
    brand: 'Waypoint Tech',
    category: 'Consumer Electronics & Appliances',
    district: 'Colombo',
    hub: 'Peliyagoda Central DC',
    address: '418 Galle Road, Colombo 03',
    manager: 'R. Senanayake',
    phone: '+94 71 334 9901',
    accessConstraint: 'Street Unload (Morning Only)',
    dockType: 'Street Curb',
    deliveryWindow: '08:30 AM – 10:30 AM',
    mustArriveBefore: '11:00 AM',
    receivingPin: '1942',
    consecutiveSkips: 0,
  },
];

// Product catalogs tailored to the 3 Waypoint brands
export const CATALOGS = {
  'Waypoint Fresh': [
    {
      id: 'PRD-F101',
      name: 'Nadu White Rice 5kg',
      category: 'Dry',
      format: 'Case of 4 (20kg)',
      unitWeightKg: 20,
      unitVolumeM3: 0.05,
    },
    {
      id: 'PRD-F102',
      name: 'Fortune Vegetable Cooking Oil 1L',
      category: 'Dry',
      format: 'Case of 12 (12L)',
      unitWeightKg: 12,
      unitVolumeM3: 0.03,
    },
    {
      id: 'PRD-F103',
      name: 'Prima Wheat All-Purpose Flour 1kg',
      category: 'Dry',
      format: 'Bundle of 20 (20kg)',
      unitWeightKg: 20,
      unitVolumeM3: 0.04,
    },
    {
      id: 'PRD-F104',
      name: 'Watawala Pure Ceylon Black Tea 400g',
      category: 'Dry',
      format: 'Box of 16 (6.4kg)',
      unitWeightKg: 6.4,
      unitVolumeM3: 0.02,
    },
    {
      id: 'PRD-F105',
      name: 'Brown Pure Cane Sugar 1kg',
      category: 'Dry',
      format: 'Case of 25 (25kg)',
      unitWeightKg: 25,
      unitVolumeM3: 0.045,
    },
    {
      id: 'PRD-F201',
      name: 'Pelwatte Fresh Pasteurized Milk 1L',
      category: 'Chilled',
      subType: 'Chilled (3°C)',
      format: 'Plastic crate of 20 (20L)',
      unitWeightKg: 22,
      unitVolumeM3: 0.06,
    },
    {
      id: 'PRD-F202',
      name: 'Anchor Pure Salted Butter 227g',
      category: 'Chilled',
      subType: 'Chilled (4°C)',
      format: 'Insulated carton of 40 (9.1kg)',
      unitWeightKg: 9.5,
      unitVolumeM3: 0.025,
    },
    {
      id: 'PRD-F203',
      name: 'Bairaha Chilled Chicken Drumsticks',
      category: 'Chilled',
      subType: 'Chilled (1°C)',
      format: 'Poly-crate of 15 packs (15kg)',
      unitWeightKg: 16,
      unitVolumeM3: 0.05,
    },
    {
      id: 'PRD-F204',
      name: 'Elephant House Vanilla & Berry Ice Cream 1L',
      category: 'Chilled',
      subType: 'Frozen (-18°C)',
      format: 'Deep freeze crate of 8 (8L)',
      unitWeightKg: 7.5,
      unitVolumeM3: 0.04,
    },
  ],
  'Waypoint Style': [
    {
      id: 'PRD-S101',
      name: 'Formal Cotton Men’s Shirts (Hanger Pack)',
      category: 'Hanging',
      subType: 'Garments on Hanger',
      format: 'Rack bundle of 24 pieces',
      unitWeightKg: 8.5,
      unitVolumeM3: 0.16, // High volume per kg
    },
    {
      id: 'PRD-S102',
      name: 'Linen Casual Trousers (Hanger Pack)',
      category: 'Hanging',
      subType: 'Garments on Hanger',
      format: 'Rack bundle of 20 pieces',
      unitWeightKg: 9.0,
      unitVolumeM3: 0.18,
    },
    {
      id: 'PRD-S103',
      name: 'Handcrafted Festive Silk Sarees',
      category: 'Hanging',
      subType: 'Garments on Hanger',
      format: 'Protective zip garment bags (12 pieces)',
      unitWeightKg: 6.0,
      unitVolumeM3: 0.14,
    },
    {
      id: 'PRD-S201',
      name: 'Men & Women Casual Footwear Collection',
      category: 'Carton',
      subType: 'Boxed Goods',
      format: 'Master carton of 16 shoe boxes',
      unitWeightKg: 18.0,
      unitVolumeM3: 0.12,
    },
    {
      id: 'PRD-S202',
      name: 'Stretch Denim Jeans Assorted Sizes',
      category: 'Carton',
      subType: 'Boxed Goods',
      format: 'Export carton of 25 pairs',
      unitWeightKg: 20.0,
      unitVolumeM3: 0.08,
    },
    {
      id: 'PRD-S203',
      name: 'Leather Belts & Wallets Accessory Packs',
      category: 'Carton',
      subType: 'Boxed Goods',
      format: 'Counter display carton of 30 pieces',
      unitWeightKg: 5.0,
      unitVolumeM3: 0.03,
    },
  ],
  'Waypoint Tech': [
    {
      id: 'PRD-T101',
      name: 'Inverter Frost-Free Refrigerator 340L',
      category: 'Major Appliance',
      subType: 'Fragile / Upright',
      format: 'Heavy crated individual unit',
      unitWeightKg: 68.0,
      unitVolumeM3: 0.95,
    },
    {
      id: 'PRD-T102',
      name: '65" 4K UHD Smart Cinema OLED TV',
      category: 'Major Appliance',
      subType: 'Fragile / Vertical Only',
      format: 'Shock-cushioned display carton',
      unitWeightKg: 28.0,
      unitVolumeM3: 0.45,
    },
    {
      id: 'PRD-T103',
      name: 'Front-Loading Automatic Washing Machine 8kg',
      category: 'Major Appliance',
      subType: 'Heavy Crated',
      format: 'Reinforced pallet carton',
      unitWeightKg: 72.0,
      unitVolumeM3: 0.65,
    },
    {
      id: 'PRD-T201',
      name: 'Digital Convection Microwave Oven 30L',
      category: 'Small Appliance',
      subType: 'Standard Boxed',
      format: 'Individual retail carton',
      unitWeightKg: 14.5,
      unitVolumeM3: 0.09,
    },
    {
      id: 'PRD-T202',
      name: 'Stainless Steel Stand Mixer & Blender Set',
      category: 'Small Appliance',
      subType: 'Standard Boxed',
      format: 'Master carton of 2 sets',
      unitWeightKg: 9.0,
      unitVolumeM3: 0.06,
    },
  ],
};

// Active inbound shipments by outlet
export const ACTIVE_INBOUND_BY_OUTLET = {
  OUT047: [
    {
      id: 'VH-014',
      vehicleType: 'Reefer Van',
      category: 'Chilled',
      schedule: 'Wave 1 · Expected 06:45 AM Today',
      status: 'Arrived at curb',
      activeStageIndex: 3,
      driver: {
        name: 'Nimal Perera',
        number: '+94 71 890 1234',
        vehicleId: 'VEH014',
      },
      milestones: [
        { label: 'Order Placed', time: 'Wed 3:45 PM' },
        { label: 'Loaded Bay A', time: 'Thu 5:10 AM' },
        { label: 'En Route', time: '05:40 AM' },
        { label: 'Arrived at Curb', time: '06:42 AM' },
      ],
      products: [
        { name: 'Pelwatte Pasteurized Milk 1L', orderNo: 'ORD-30082', category: 'Chilled (3°C)', quantity: '15 crates (300L)', verified: true },
        { name: 'Anchor Pure Salted Butter 227g', orderNo: 'ORD-30082', category: 'Chilled (4°C)', quantity: '6 cartons', verified: true },
        { name: 'Bairaha Chilled Chicken Drumsticks', orderNo: 'ORD-30082', category: 'Chilled (1°C)', quantity: '4 crates', verified: true },
      ],
    },
    {
      id: 'VH-003',
      vehicleType: 'Dry Box Van',
      category: 'Dry',
      schedule: 'Wave 1 · Expected 07:15 AM Today',
      status: 'Out for delivery',
      activeStageIndex: 2,
      driver: {
        name: 'K. Bandara',
        number: '+94 77 441 2980',
        vehicleId: 'VEH003',
      },
      milestones: [
        { label: 'Order Placed', time: 'Wed 3:45 PM' },
        { label: 'Loaded Bay C', time: 'Thu 5:30 AM' },
        { label: 'En Route', time: '06:10 AM' },
        { label: 'Arrived at Curb', time: 'Est. 07:15 AM' },
      ],
      products: [
        { name: 'Nadu White Rice 5kg', orderNo: 'ORD-30081', category: 'Dry Grocery', quantity: '8 cases (160kg)', verified: true },
        { name: 'Fortune Vegetable Cooking Oil 1L', orderNo: 'ORD-30081', category: 'Dry Grocery', quantity: '5 cases (60L)', verified: true },
      ],
    },
  ],
  'OUT-4089': [
    {
      id: 'VH-011',
      vehicleType: 'Reefer Truck',
      category: 'Chilled',
      schedule: 'Wave 1 · Expected 07:20 AM Today',
      status: 'Disruption · Reassigned to VEH014',
      activeStageIndex: 2,
      driver: {
        name: 'S. Fernando',
        number: '+94 77 812 3901',
        vehicleId: 'VEH014 (Recovery Trip 2)',
      },
      milestones: [
        { label: 'Order Placed', time: 'Wed 3:55 PM' },
        { label: 'Dock Incident', time: 'Hydraulic seizure' },
        { label: 'Recovery Slot', time: 'Reassigned 08:35 AM' },
        { label: 'Revised Arrival', time: 'Est. 09:45 AM' },
      ],
      products: [
        { name: 'Pelwatte Pasteurized Milk 1L', orderNo: 'ORD-30114', category: 'Chilled', quantity: '12 crates', verified: false },
      ],
    },
  ],
  'OUT-2041': [
    {
      id: 'VH-025',
      vehicleType: 'High-Cube Dry Truck',
      category: 'Style (Apparel)',
      schedule: 'Weekly Run · Mall Window 07:00–09:00 AM',
      status: 'Arrived at mall dock',
      activeStageIndex: 3,
      driver: {
        name: 'G. Jayasinghe',
        number: '+94 72 331 4455',
        vehicleId: 'VEH025',
      },
      milestones: [
        { label: 'Weekly Cutoff', time: 'Tue 4:00 PM' },
        { label: 'Staged Bay 2', time: 'Thu 4:00 AM' },
        { label: 'Expressway Run', time: 'Thu 6:00 AM' },
        { label: 'Mall Dock Bay 1', time: '07:15 AM' },
      ],
      products: [
        { name: 'Formal Cotton Men’s Shirts (Hanger Pack)', orderNo: 'ORD-29901', category: 'Hanging Garments', quantity: '18 racks (432 pcs)', verified: true },
        { name: 'Men & Women Casual Footwear Collection', orderNo: 'ORD-29901', category: 'Cartons', quantity: '8 master cartons', verified: true },
      ],
    },
  ],
  'OUT-1029': [
    {
      id: 'VH-040',
      vehicleType: 'Tail-Lift Heavy Box Truck',
      category: 'Major Appliances',
      schedule: 'As-Needed · Expected 09:30 AM',
      status: 'Disruption Deferred',
      activeStageIndex: 1,
      driver: {
        name: 'Dispatch Office',
        number: '+94 11 244 5500',
        vehicleId: 'Pending Recovery',
      },
      milestones: [
        { label: 'Order Placed', time: 'Wed 2:30 PM' },
        { label: 'Vehicle Breakdown', time: 'VEH006 en route' },
        { label: 'Deferred Notice', time: 'Published 08:31 AM' },
        { label: 'Next Run', time: 'Guaranteed Fri Wave 1' },
      ],
      products: [
        { name: 'Inverter Frost-Free Refrigerator 340L', orderNo: 'ORD-30088', category: 'Major Appliance', quantity: '2 units', verified: false },
        { name: '65" 4K UHD Smart Cinema OLED TV', orderNo: 'ORD-30088', category: 'Major Appliance', quantity: '3 units', verified: false },
      ],
    },
  ],
};

// Historical orders for Receipts & Deferrals tab
export const ORDER_HISTORY_BY_OUTLET = {
  OUT047: [
    {
      date: 'Today · Sep 29',
      orderNo: 'ORD-30082',
      product: 'Pelwatte Milk & Chilled Chicken',
      quantity: '25 crates (Chilled)',
      type: 'Chilled Run',
      outcome: 'Delivered',
      deliveryTruck: 'VEH014 (Van Reefer)',
      deliveryTime: '06:42 AM',
      pinUsed: '4829',
      driverName: 'Nimal Perera',
    },
    {
      date: 'Today · Sep 29',
      orderNo: 'ORD-30081',
      product: 'Nadu Rice & Fortune Cooking Oil',
      quantity: '13 cases (Dry)',
      type: 'Dry Grocery',
      outcome: 'In Transit',
      deliveryTruck: 'VEH003 (Dry Van)',
      deliveryTime: 'Est. 07:15 AM',
      pinUsed: 'Pending',
      driverName: 'K. Bandara',
    },
    {
      date: 'Sep 26',
      orderNo: 'ORD-29840',
      product: 'Dry Groceries & Tea cases',
      quantity: '18 cases',
      type: 'Dry Grocery',
      outcome: 'Delivered',
      deliveryTruck: 'VEH004',
      deliveryTime: '07:22 AM',
      pinUsed: '4829',
      driverName: 'P. Jayasuriya',
    },
    {
      date: 'Sep 24',
      orderNo: 'ORD-29712',
      product: 'Chilled Dairy & Poultry Packs',
      quantity: '20 crates',
      type: 'Chilled Run',
      outcome: 'Deferred',
      deferralReason: 'Kandy hub reefer capacity short ahead of Payday surge. Auto-scheduled for Friday Wave 1.',
      antiStarvationProtection: true,
      highlight: true,
    },
  ],
  'OUT-4089': [
    {
      date: 'Today · Sep 29',
      orderNo: 'ORD-30114',
      product: 'Chilled Dairy Packs',
      quantity: '12 crates',
      type: 'Chilled Run',
      outcome: 'Deferred',
      deferralReason: 'VEH011 hydraulic lift failure at Peliyagoda Bay 3. Rescheduled to VEH014 Trip 2 (New ETA: 09:45 AM).',
      antiStarvationProtection: true,
      highlight: true,
    },
    {
      date: 'Sep 27',
      orderNo: 'ORD-29930',
      product: 'Dry Groceries + Anchor Butter',
      quantity: '22 cases',
      type: 'Dry + Chilled',
      outcome: 'Delivered',
      deliveryTruck: 'VEH010',
      deliveryTime: '07:35 AM',
      pinUsed: '6194',
      driverName: 'L. Senaratne',
    },
  ],
  'OUT-1029': [
    {
      date: 'Today · Sep 29',
      orderNo: 'ORD-30088',
      product: 'Inverter Refrigerators & 65" OLED TVs',
      quantity: '5 units',
      type: 'Heavy Fragile',
      outcome: 'Deferred',
      deferralReason: 'VEH006 coolant leak on A1 Highway. Fresh window closed before secondary departure slot. Priority 1 assigned.',
      antiStarvationProtection: true,
      highlight: true,
    },
  ],
  'OUT-2041': [
    {
      date: 'Today · Sep 29',
      orderNo: 'ORD-29901',
      product: 'Hanging Shirts & Footwear Master Cartons',
      quantity: '26 units (Volume-Heavy)',
      type: 'Apparel Cartons',
      outcome: 'Delivered',
      deliveryTruck: 'VEH025',
      deliveryTime: '07:18 AM',
      pinUsed: '3318',
      driverName: 'G. Jayasinghe',
    },
  ],
};
