"""Initial Phase 1

Revision ID: cffd139ab054
Revises: 
Create Date: 2026-10-02 12:00:02.444938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cffd139ab054'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depot',
    sa.Column('depot_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('lng', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('depot_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('temp_req', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_wt_kg', sa.Numeric(), nullable=True),
    sa.Column('unit_vol_m3', sa.Numeric(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('outlet',
    sa.Column('outlet_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('depot_id', sa.String(), nullable=True),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('lng', sa.Numeric(), nullable=True),
    sa.Column('window_open', sa.String(), nullable=True),
    sa.Column('window_close', sa.String(), nullable=True),
    sa.Column('mall_window', sa.String(), nullable=True),
    sa.Column('dock_type', sa.String(), nullable=True),
    sa.Column('park_constraint', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['depot_id'], ['depot.depot_id'], ),
    sa.PrimaryKeyConstraint('outlet_id')
    )
    op.create_table('vehicle',
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('depot_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('temp', sa.String(), nullable=False),
    sa.Column('weight_cap_kg', sa.Numeric(), nullable=False),
    sa.Column('vol_cap_m3', sa.Numeric(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('km_per_l', sa.Numeric(), nullable=True),
    sa.Column('fuel_quota_l', sa.Integer(), nullable=True),
    sa.Column('plate', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_lat', sa.Numeric(), nullable=True),
    sa.Column('last_lng', sa.Numeric(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['depot_id'], ['depot.depot_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('outlet_id', sa.String(), nullable=True),
    sa.Column('depot_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_pw', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depot.depot_id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.outlet_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('order',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('outlet_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('temp_req', sa.String(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('order_units', sa.Integer(), nullable=True),
    sa.Column('order_wt_kg', sa.Numeric(), nullable=True),
    sa.Column('order_vol_m3', sa.Numeric(), nullable=True),
    sa.Column('window_open', sa.String(), nullable=True),
    sa.Column('window_close', sa.String(), nullable=True),
    sa.Column('trip_id', sa.String(), nullable=True),
    sa.Column('stop_seq', sa.Integer(), nullable=True),
    sa.Column('exp_arrival', sa.String(), nullable=True),
    sa.Column('actual_arrival', sa.String(), nullable=True),
    sa.Column('deferred_prev', sa.Boolean(), nullable=False),
    sa.Column('defer_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.outlet_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('outlet_id', 'order_date', 'temp_req', name='uix_order_outlet_date_temp')
    )
    op.create_table('order_line',
    sa.Column('line_item_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('line_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_line')
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('vehicle')
    op.drop_table('outlet')
    op.drop_table('product')
    op.drop_table('depot')
    # ### end Alembic commands ###
