"""Add driver_id and phone

Revision ID: b809c6fef069
Revises: b2c3d4e5f6a7
Create Date: 2026-10-04 14:08:09.921870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b809c6fef069'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('vehicle', sa.Column('driver_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'vehicle', 'user', ['driver_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'vehicle', type_='foreignkey')
    op.drop_column('vehicle', 'driver_id')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
