"""add_fk_order_trip_id

Revision ID: 354f44f89c24
Revises: a1b2c3d4e5f6
Create Date: 2026-10-02 21:11:21.888935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354f44f89c24'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_order_trip_id', 'order', 'trip', ['trip_id'], ['trip_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_order_trip_id', 'order', type_='foreignkey')
    # ### end Alembic commands ###
